Hi🅱️🅱️opotamous
RIT-EVT/HIB pull request #1
Opened 2024-02-03 17:53 UTC by ol2764RIT

Setup for new project!

2024-02-09 04:19 UTC, mjmagee991 requested changes
A couple quick changes

2024-02-09 04:19 UTC, mjmagee991 commented on CMakeLists.txt
> +# Top level CMakeList for building the *EVT_HIB* source code
```suggestion
# Top level CMakeList for building the HIB source code
```

2024-02-09 04:19 UTC, mjmagee991 commented on README.md
> +Handlebar Interface Board (HIB). This board is capable of taking an analog input from the potentiometer based throttle and converting it to a digital signal with the use of an SPC58 microcontroller.
```suggestion
Handlebar Interface Board (HIB). This board is capable of taking an analog input from the potentiometer based throttle and converting it to a digital signal with the use of an STM32 microcontroller. This board is used to read the analog throttle signal and transmit it as a CAN message. There are ADCs for throttle and brake functionality. The board also has CAN loopback hardware for self-testing.
```

2024-02-09 22:48 UTC, mjmagee991 approved these changes
Nice work!

2024-02-13 00:03 UTC, ActuallyTaylor approved these changes

2024-02-13 00:13 UTC, merged